[2025-04-27T15:00:56.958+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: email_sender.extract_data manual__2025-04-27T15:00:56.248456+00:00 [queued]>
[2025-04-27T15:00:56.961+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: email_sender.extract_data manual__2025-04-27T15:00:56.248456+00:00 [queued]>
[2025-04-27T15:00:56.961+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-27T15:00:56.966+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_data> on 2025-04-27 15:00:56.248456+00:00
[2025-04-27T15:00:56.968+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2025-04-27T15:00:56.970+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'email_sender', 'extract_data', 'manual__2025-04-27T15:00:56.248456+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/email_sender_dag.py', '--cfg-path', '/tmp/tmp9sxg64f2']
[2025-04-27T15:00:56.971+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask extract_data
[2025-04-27T15:00:57.077+0000] {task_command.py:423} INFO - Running <TaskInstance: email_sender.extract_data manual__2025-04-27T15:00:56.248456+00:00 [running]> on host ebc446b713fb
[2025-04-27T15:00:57.101+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='email_sender' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-27T15:00:56.248456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-27T15:00:56.248456+00:00'
[2025-04-27T15:00:57.104+0000] {base.py:83} INFO - Using connection ID 'postgresql_padrao' for task execution.
[2025-04-27T15:00:57.118+0000] {warnings.py:109} WARNING - /opt/***/dags/email_sender_dag.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql_query, conn)

[2025-04-27T15:00:57.130+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-27T15:00:57.133+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=email_sender, task_id=extract_data, execution_date=20250427T150056, start_date=20250427T150056, end_date=20250427T150057
[2025-04-27T15:00:57.147+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-27T15:00:57.220+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
